### ISSUE TITLE
Integration asking for MAC Address

### ISSUE THREAD

**Issue by pszober** [bkbilly/hass-oralb#1]
Hi,

I tried integrating my Oral B toothbrushes using this integration to compare it with the official one. I understand that the documentation says that it won't auto-discover toothbrushes like the official integration does so I tried adding it manually. The problem is that it is asking me for MAC address of the toothbrush and I have no idea how to obtain it. I tried googling it but there's no more documentation anywhere and there seems to be nothing on any forum just yet.

Would you mind explaining how does the process of adding a new toothbrush work? Thanks.

**Comment by bkbilly** [comment]
I created this before the official integration and I published it because the official didn't support the battery because it needed active connection which is now fixed.
If you want to get the mac, you can use a BLE Scanner on your phone like the **nRF Connect**.

**Comment by pszober** [comment]
That's great. Thanks a lot for your reply.
